export const LIST = {
    "trends": [
        {
            "symbol": "AVT:NASDAQ",
            "type": "stock",
            "name": "Avnet Inc",
            "price": 48.58,
            "change": 3.63,
            "change_percent": 8.0756,
            "previous_close": 44.95,
            "pre_or_post_market": 48.58,
            "pre_or_post_market_change": 0,
            "pre_or_post_market_change_percent": 0,
            "last_update_utc": "2023-08-18 00:30:00",
            "currency": "USD",
            "exchange": "NASDAQ",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/m/07zkt56"
        },
        {
            "symbol": "AMC:NYSE",
            "type": "stock",
            "name": "AMC Entertainment Holdings Inc",
            "price": 4.04,
            "change": 0.29,
            "change_percent": 7.7333,
            "previous_close": 3.75,
            "pre_or_post_market": 4.17,
            "pre_or_post_market_change": 0.13,
            "pre_or_post_market_change_percent": 3.2178,
            "last_update_utc": "2023-08-18 00:04:00",
            "currency": "USD",
            "exchange": "NYSE",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/g/1ym82y1nc"
        },
        {
            "symbol": "MRNA:NASDAQ",
            "type": "stock",
            "name": "Moderna Inc",
            "price": 106.24,
            "change": 7.32,
            "change_percent": 7.3999,
            "previous_close": 98.92,
            "pre_or_post_market": 106.21,
            "pre_or_post_market_change": -0.03,
            "pre_or_post_market_change_percent": -0.0282,
            "last_update_utc": "2023-08-18 00:30:00",
            "currency": "USD",
            "exchange": "NASDAQ",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/g/11fht_cn6q"
        },
        {
            "symbol": "FHB:NASDAQ",
            "type": "stock",
            "name": "First Hawaiian Inc",
            "price": 19.46,
            "change": 0.88,
            "change_percent": 4.7363,
            "previous_close": 18.58,
            "pre_or_post_market": 19.46,
            "pre_or_post_market_change": 0,
            "pre_or_post_market_change_percent": 0,
            "last_update_utc": "2023-08-18 00:30:00",
            "currency": "USD",
            "exchange": "NASDAQ",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/g/11c0vn9gm3"
        },
        {
            "symbol": "CHK:NASDAQ",
            "type": "stock",
            "name": "Chesapeake Energy Ord Shs",
            "price": 86.25,
            "change": 3.67,
            "change_percent": 4.4442,
            "previous_close": 82.58,
            "pre_or_post_market": 86.4,
            "pre_or_post_market_change": 0.15,
            "pre_or_post_market_change_percent": 0.1739,
            "last_update_utc": "2023-08-18 00:30:00",
            "currency": "USD",
            "exchange": "NASDAQ",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/m/07zm5s4"
        },
        {
            "symbol": "TECK:NYSE",
            "type": "stock",
            "name": "Teck Resources Ltd Class B",
            "price": 38.63,
            "change": 1.37,
            "change_percent": 3.6769,
            "previous_close": 37.26,
            "pre_or_post_market": 38.8,
            "pre_or_post_market_change": 0.17,
            "pre_or_post_market_change_percent": 0.4401,
            "last_update_utc": "2023-08-18 00:04:00",
            "currency": "USD",
            "exchange": "NYSE",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/m/07zmbz5"
        },
        {
            "symbol": "BOH:NYSE",
            "type": "stock",
            "name": "Bank of Hawaii Corp",
            "price": 54.39,
            "change": 1.91,
            "change_percent": 3.6395,
            "previous_close": 52.48,
            "pre_or_post_market": 54.2,
            "pre_or_post_market_change": -0.19,
            "pre_or_post_market_change_percent": -0.3493,
            "last_update_utc": "2023-08-18 00:04:01",
            "currency": "USD",
            "exchange": "NYSE",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/m/07zlyng"
        },
        {
            "symbol": "NFE:NASDAQ",
            "type": "stock",
            "name": "New Fortress Energy Inc",
            "price": 29.07,
            "change": 1.02,
            "change_percent": 3.6364,
            "previous_close": 28.05,
            "pre_or_post_market": 29.785,
            "pre_or_post_market_change": 0.715,
            "pre_or_post_market_change_percent": 2.4596,
            "last_update_utc": "2023-08-18 00:30:00",
            "currency": "USD",
            "exchange": "NASDAQ",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/g/11fjndwkyn"
        },
        {
            "symbol": "CSCO:NASDAQ",
            "type": "stock",
            "name": "Cisco Systems Inc",
            "price": 54.73,
            "change": 1.77,
            "change_percent": 3.3421,
            "previous_close": 52.96,
            "pre_or_post_market": 54.7,
            "pre_or_post_market_change": -0.03,
            "pre_or_post_market_change_percent": -0.0548,
            "last_update_utc": "2023-08-18 00:30:00",
            "currency": "USD",
            "exchange": "NASDAQ",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/m/07zm4wq"
        },
        {
            "symbol": "APE:NYSE",
            "type": "stock",
            "name": "AMC Entertainment Hldg Pref Equity Units Depositary Share Rep 1 100th Int Convertible Prf Shs Series A",
            "price": 2.19,
            "change": 0.07,
            "change_percent": 3.3019,
            "previous_close": 2.12,
            "pre_or_post_market": 2.2099,
            "pre_or_post_market_change": 0.0199,
            "pre_or_post_market_change_percent": 0.9087,
            "last_update_utc": "2023-08-18 00:04:01",
            "currency": "USD",
            "exchange": "NYSE",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/g/11s650nbqs"
        },
        {
            "symbol": "ODD:NASDAQ",
            "type": "stock",
            "name": "Oddity Tech Ltd",
            "price": 45.31,
            "change": 1.36,
            "change_percent": 3.0944,
            "previous_close": 43.95,
            "pre_or_post_market": 45,
            "pre_or_post_market_change": -0.31,
            "pre_or_post_market_change_percent": -0.6842,
            "last_update_utc": "2023-08-18 00:30:00",
            "currency": "USD",
            "exchange": "NASDAQ",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/g/11krbqnr9k"
        },
        {
            "symbol": "JNPR:NYSE",
            "type": "stock",
            "name": "Juniper Networks, Inc.",
            "price": 27.95,
            "change": 0.83,
            "change_percent": 3.0605,
            "previous_close": 27.12,
            "pre_or_post_market": 27.95,
            "pre_or_post_market_change": 0,
            "pre_or_post_market_change_percent": 0,
            "last_update_utc": "2023-08-18 00:04:00",
            "currency": "USD",
            "exchange": "NYSE",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/m/07zlcg7"
        },
        {
            "symbol": "SN:NYSE",
            "type": "stock",
            "name": "SharkNinja Ord Shs",
            "price": 31.22,
            "change": 0.92,
            "change_percent": 3.0363,
            "previous_close": 30.3,
            "pre_or_post_market": 31.2,
            "pre_or_post_market_change": -0.02,
            "pre_or_post_market_change_percent": -0.0641,
            "last_update_utc": "2023-08-18 00:04:01",
            "currency": "USD",
            "exchange": "NYSE",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/g/11g7y74pf2"
        },
        {
            "symbol": "PFE:NYSE",
            "type": "stock",
            "name": "Pfizer Inc.",
            "price": 36.51,
            "change": 1.03,
            "change_percent": 2.903,
            "previous_close": 35.48,
            "pre_or_post_market": 36.55,
            "pre_or_post_market_change": 0.04,
            "pre_or_post_market_change_percent": 0.1096,
            "last_update_utc": "2023-08-18 00:04:00",
            "currency": "USD",
            "exchange": "NYSE",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/m/07zkz5s"
        },
        {
            "symbol": "MTDR:NYSE",
            "type": "stock",
            "name": "Matador Resources Co",
            "price": 60.37,
            "change": 1.59,
            "change_percent": 2.705,
            "previous_close": 58.78,
            "pre_or_post_market": 60.37,
            "pre_or_post_market_change": 0,
            "pre_or_post_market_change_percent": 0,
            "last_update_utc": "2023-08-18 00:04:00",
            "currency": "USD",
            "exchange": "NYSE",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/g/1hbvsnstm"
        },
        {
            "symbol": "NOMD:NYSE",
            "type": "stock",
            "name": "Nomad Foods Ltd",
            "price": 17.85,
            "change": 0.47,
            "change_percent": 2.7043,
            "previous_close": 17.38,
            "pre_or_post_market": 17.85,
            "pre_or_post_market_change": 0,
            "pre_or_post_market_change_percent": 0,
            "last_update_utc": "2023-08-18 00:04:01",
            "currency": "USD",
            "exchange": "NYSE",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/g/11bbx0ljxd"
        },
        {
            "symbol": "TPL:NYSE",
            "type": "stock",
            "name": "Texas Pacific Land Corp",
            "price": 1908.48,
            "change": 50.1,
            "change_percent": 2.6959,
            "previous_close": 1858.38,
            "pre_or_post_market": null,
            "pre_or_post_market_change": null,
            "pre_or_post_market_change_percent": null,
            "last_update_utc": "2023-08-18 00:04:00",
            "currency": "USD",
            "exchange": "NYSE",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/m/03p39zp"
        },
        {
            "symbol": "VIAV:NASDAQ",
            "type": "stock",
            "name": "Viavi Solutions Inc",
            "price": 10.14,
            "change": 0.26,
            "change_percent": 2.6316,
            "previous_close": 9.88,
            "pre_or_post_market": 10.14,
            "pre_or_post_market_change": 0,
            "pre_or_post_market_change_percent": 0,
            "last_update_utc": "2023-08-18 00:30:00",
            "currency": "USD",
            "exchange": "NASDAQ",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/m/07zks3v"
        },
        {
            "symbol": "PR:NYSE",
            "type": "stock",
            "name": "Permian Resources Corp",
            "price": 12.55,
            "change": 0.32,
            "change_percent": 2.6165,
            "previous_close": 12.23,
            "pre_or_post_market": 12.7,
            "pre_or_post_market_change": 0.15,
            "pre_or_post_market_change_percent": 1.1952,
            "last_update_utc": "2023-08-18 00:04:01",
            "currency": "USD",
            "exchange": "NYSE",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/g/11dx9hdq1_"
        },
        {
            "symbol": "MRCY:NASDAQ",
            "type": "stock",
            "name": "Mercury Systems Inc",
            "price": 37.09,
            "change": 0.92,
            "change_percent": 2.5436,
            "previous_close": 36.17,
            "pre_or_post_market": 37.1,
            "pre_or_post_market_change": 0.01,
            "pre_or_post_market_change_percent": 0.027,
            "last_update_utc": "2023-08-18 00:30:00",
            "currency": "USD",
            "exchange": "NASDAQ",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/m/07zl4cd"
        },
        {
            "symbol": "SU:NYSE",
            "type": "stock",
            "name": "Suncor Energy Inc",
            "price": 32.63,
            "change": 0.78,
            "change_percent": 2.449,
            "previous_close": 31.85,
            "pre_or_post_market": 32.73,
            "pre_or_post_market_change": 0.1,
            "pre_or_post_market_change_percent": 0.3065,
            "last_update_utc": "2023-08-18 00:04:00",
            "currency": "USD",
            "exchange": "NYSE",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/m/07zlwhh"
        },
        {
            "symbol": "KEY:NYSE",
            "type": "stock",
            "name": "KeyCorp",
            "price": 10.78,
            "change": 0.25,
            "change_percent": 2.3742,
            "previous_close": 10.53,
            "pre_or_post_market": 10.78,
            "pre_or_post_market_change": 0,
            "pre_or_post_market_change_percent": 0,
            "last_update_utc": "2023-08-18 00:04:00",
            "currency": "USD",
            "exchange": "NYSE",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/m/07zlpqs"
        },
        {
            "symbol": "DFS:NYSE",
            "type": "stock",
            "name": "Discover Financial Services",
            "price": 92.38,
            "change": 2.12,
            "change_percent": 2.3488,
            "previous_close": 90.26,
            "pre_or_post_market": 92.09,
            "pre_or_post_market_change": -0.29,
            "pre_or_post_market_change_percent": -0.3139,
            "last_update_utc": "2023-08-18 00:04:00",
            "currency": "USD",
            "exchange": "NYSE",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/m/07zlvn_"
        },
        {
            "symbol": "MUR:NYSE",
            "type": "stock",
            "name": "Murphy Oil Corp",
            "price": 45.09,
            "change": 1.03,
            "change_percent": 2.3377,
            "previous_close": 44.06,
            "pre_or_post_market": 45.09,
            "pre_or_post_market_change": 0,
            "pre_or_post_market_change_percent": 0,
            "last_update_utc": "2023-08-18 00:04:00",
            "currency": "USD",
            "exchange": "NYSE",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/m/07zl86g"
        },
        {
            "symbol": "EMN:NYSE",
            "type": "stock",
            "name": "Eastman Chemical Co",
            "price": 83.18,
            "change": 1.89,
            "change_percent": 2.325,
            "previous_close": 81.29,
            "pre_or_post_market": 83.18,
            "pre_or_post_market_change": 0,
            "pre_or_post_market_change_percent": 0,
            "last_update_utc": "2023-08-18 00:04:00",
            "currency": "USD",
            "exchange": "NYSE",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/m/07zl7sy"
        },
        {
            "symbol": "AR:NYSE",
            "type": "stock",
            "name": "Antero Resources Corp",
            "price": 27.73,
            "change": 0.63,
            "change_percent": 2.3247,
            "previous_close": 27.1,
            "pre_or_post_market": 27.73,
            "pre_or_post_market_change": 0,
            "pre_or_post_market_change_percent": 0,
            "last_update_utc": "2023-08-18 00:04:00",
            "currency": "USD",
            "exchange": "NYSE",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/g/12xnpnf4s"
        },
        {
            "symbol": "XRX:NASDAQ",
            "type": "stock",
            "name": "Xerox Holdings Corp",
            "price": 15.13,
            "change": 0.34,
            "change_percent": 2.2989,
            "previous_close": 14.79,
            "pre_or_post_market": 15.13,
            "pre_or_post_market_change": 0,
            "pre_or_post_market_change_percent": 0,
            "last_update_utc": "2023-08-18 00:30:00",
            "currency": "USD",
            "exchange": "NASDAQ",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/m/07zlgk1"
        },
        {
            "symbol": "KOS:NYSE",
            "type": "stock",
            "name": "Kosmos Energy Ltd",
            "price": 7.31,
            "change": 0.16,
            "change_percent": 2.2378,
            "previous_close": 7.15,
            "pre_or_post_market": 7.31,
            "pre_or_post_market_change": 0,
            "pre_or_post_market_change_percent": 0,
            "last_update_utc": "2023-08-18 00:04:00",
            "currency": "USD",
            "exchange": "NYSE",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/g/1dv6wfl5"
        },
        {
            "symbol": "EQT:NYSE",
            "type": "stock",
            "name": "EQT Corp",
            "price": 42.91,
            "change": 0.93,
            "change_percent": 2.2153,
            "previous_close": 41.98,
            "pre_or_post_market": 43.04,
            "pre_or_post_market_change": 0.13,
            "pre_or_post_market_change_percent": 0.303,
            "last_update_utc": "2023-08-18 00:04:00",
            "currency": "USD",
            "exchange": "NYSE",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/m/07zk_cz"
        },
        {
            "symbol": "SWN:NYSE",
            "type": "stock",
            "name": "Southwestern Energy Co",
            "price": 6.56,
            "change": 0.14,
            "change_percent": 2.1807,
            "previous_close": 6.42,
            "pre_or_post_market": 6.57,
            "pre_or_post_market_change": 0.01,
            "pre_or_post_market_change_percent": 0.1524,
            "last_update_utc": "2023-08-18 00:04:00",
            "currency": "USD",
            "exchange": "NYSE",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/m/07zlhqr"
        },
        {
            "symbol": "SM:NYSE",
            "type": "stock",
            "name": "SM Energy Co",
            "price": 40.31,
            "change": 0.86,
            "change_percent": 2.18,
            "previous_close": 39.45,
            "pre_or_post_market": 40.31,
            "pre_or_post_market_change": 0,
            "pre_or_post_market_change_percent": 0,
            "last_update_utc": "2023-08-18 00:04:00",
            "currency": "USD",
            "exchange": "NYSE",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/m/07zl9kx"
        },
        {
            "symbol": "EURN:NYSE",
            "type": "stock",
            "name": "Euronav NV",
            "price": 18.16,
            "change": 0.38,
            "change_percent": 2.1372,
            "previous_close": 17.78,
            "pre_or_post_market": 18.16,
            "pre_or_post_market_change": 0,
            "pre_or_post_market_change_percent": 0,
            "last_update_utc": "2023-08-18 00:04:00",
            "currency": "USD",
            "exchange": "NYSE",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/g/1dv3vlrr"
        },
        {
            "symbol": "VIRT:NASDAQ",
            "type": "stock",
            "name": "Virtu Financial Inc",
            "price": 19.25,
            "change": 0.4,
            "change_percent": 2.122,
            "previous_close": 18.85,
            "pre_or_post_market": 19.25,
            "pre_or_post_market_change": 0,
            "pre_or_post_market_change_percent": 0,
            "last_update_utc": "2023-08-18 00:30:00",
            "currency": "USD",
            "exchange": "NASDAQ",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/g/1pzz2clws"
        },
        {
            "symbol": "PNFPP:NASDAQ",
            "type": "stock",
            "name": "Pinnacle Finl Partners 40 DS Rep Ord Shs Series B",
            "price": 21.7,
            "change": 0.45,
            "change_percent": 2.1177,
            "previous_close": 21.25,
            "pre_or_post_market": null,
            "pre_or_post_market_change": null,
            "pre_or_post_market_change_percent": null,
            "last_update_utc": "2023-08-18 00:30:00",
            "currency": "USD",
            "exchange": "NASDAQ",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/g/11j6qyl9vf"
        },
        {
            "symbol": "RRC:NYSE",
            "type": "stock",
            "name": "Range Resources Corp",
            "price": 32.32,
            "change": 0.66,
            "change_percent": 2.0846,
            "previous_close": 31.66,
            "pre_or_post_market": 32.32,
            "pre_or_post_market_change": 0,
            "pre_or_post_market_change_percent": 0,
            "last_update_utc": "2023-08-18 00:04:00",
            "currency": "USD",
            "exchange": "NYSE",
            "exchange_open": "2023-08-17 09:30:00",
            "exchange_close": "2023-08-17 16:00:00",
            "timezone": "America/New_York",
            "utc_offset_sec": -14400,
            "country_code": "US",
            "google_mid": "/m/07zm1d8"
        }
    ],
    "news": [
        {
            "article_title": "Xerox Holdings Corp. stock outperforms market on strong trading day",
            "article_url": "https://www.marketwatch.com/data-news/xerox-holdings-corp-stock-outperforms-market-on-strong-trading-day-f39cbc98-5c735ec6e0e5",
            "article_photo_url": "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRue2tAqAKpGseiiRxi9f8egdXw79UkdTs-w3olSuZcsGPSd1Nx7AbUxnTmYqo",
            "source": "MarketWatch",
            "post_time_utc": "2023-08-17 21:35:00",
            "stocks_in_news": [
                {
                    "symbol": "XRX:NASDAQ",
                    "type": "stock",
                    "name": "Xerox Holdings Corp",
                    "price": 15.13,
                    "change": 0.34,
                    "change_percent": 2.2989,
                    "previous_close": 14.79,
                    "pre_or_post_market": 15.13,
                    "pre_or_post_market_change": 0,
                    "pre_or_post_market_change_percent": 0,
                    "last_update_utc": "2023-08-18 00:30:00",
                    "currency": "USD",
                    "exchange": "NASDAQ",
                    "exchange_open": "2023-08-17 09:30:00",
                    "exchange_close": "2023-08-17 16:00:00",
                    "timezone": "America/New_York",
                    "utc_offset_sec": -14400,
                    "country_code": "US",
                    "google_mid": "/m/07zlgk1"
                }
            ]
        },
        {
            "article_title": "Energy stocks boost TSX, Teck Resources surges",
            "article_url": "https://www.reuters.com/markets/tsx-futures-inch-higher-gains-oil-prices-2023-08-17/",
            "article_photo_url": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQEVKuTGrSiRhmQ9sw1ot3_hJhKQyzpVtz-bgeNY3u5Iqe9T91-BD3f2lnd-BA",
            "source": "Reuters",
            "post_time_utc": "2023-08-17 14:50:00",
            "stocks_in_news": [
                {
                    "symbol": "JSWSTEEL:NSE",
                    "type": "stock",
                    "name": "JSW Steel Limited",
                    "price": 787.5,
                    "change": -2.25,
                    "change_percent": -0.2849,
                    "previous_close": 789.75,
                    "pre_or_post_market": null,
                    "pre_or_post_market_change": null,
                    "pre_or_post_market_change_percent": null,
                    "last_update_utc": "2023-08-18 04:18:11",
                    "currency": "INR",
                    "exchange": "NSE",
                    "exchange_open": "2023-08-18 09:15:00",
                    "exchange_close": "2023-08-18 15:30:00",
                    "timezone": "Asia/Calcutta",
                    "utc_offset_sec": 19800,
                    "country_code": "IN",
                    "google_mid": "/g/1dv294zd"
                }
            ]
        },
        {
            "article_title": "Stocks making the biggest premarket moves: Walmart, Adobe, Cisco, Hawaiian \nElectric and more",
            "article_url": "https://www.cnbc.com/2023/08/17/stocks-making-the-biggest-premarket-moves-.html",
            "article_photo_url": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQFC5quHxr7HQU-Nm6Dp7nFFUgO-KRM_ssoEgakKl9IaBSqORFnJTk2R43ySek",
            "source": "CNBC",
            "post_time_utc": "2023-08-17 12:28:58",
            "stocks_in_news": [
                {
                    "symbol": "WMT:NYSE",
                    "type": "stock",
                    "name": "Walmart Inc",
                    "price": 155.69,
                    "change": -3.57,
                    "change_percent": -2.2416,
                    "previous_close": 159.26,
                    "pre_or_post_market": 155.3,
                    "pre_or_post_market_change": -0.39,
                    "pre_or_post_market_change_percent": -0.2505,
                    "last_update_utc": "2023-08-18 00:04:00",
                    "currency": "USD",
                    "exchange": "NYSE",
                    "exchange_open": "2023-08-17 09:30:00",
                    "exchange_close": "2023-08-17 16:00:00",
                    "timezone": "America/New_York",
                    "utc_offset_sec": -14400,
                    "country_code": "US",
                    "google_mid": "/m/07zlm7d"
                },
                {
                    "symbol": "CSCO:NASDAQ",
                    "type": "stock",
                    "name": "Cisco Systems Inc",
                    "price": 54.73,
                    "change": 1.77,
                    "change_percent": 3.3421,
                    "previous_close": 52.96,
                    "pre_or_post_market": 54.7,
                    "pre_or_post_market_change": -0.03,
                    "pre_or_post_market_change_percent": -0.0548,
                    "last_update_utc": "2023-08-18 00:30:00",
                    "currency": "USD",
                    "exchange": "NASDAQ",
                    "exchange_open": "2023-08-17 09:30:00",
                    "exchange_close": "2023-08-17 16:00:00",
                    "timezone": "America/New_York",
                    "utc_offset_sec": -14400,
                    "country_code": "US",
                    "google_mid": "/m/07zm4wq"
                }
            ]
        },
        {
            "article_title": "Mercury Systems (MRCY) Falls 11% as Q4 Earnings Miss Estimates",
            "article_url": "https://www.zacks.com/stock/news/2136827/mercury-systems-mrcy-falls-11-as-q4-earnings-miss-estimates",
            "article_photo_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJ19qtB_dzrCM8RBk8eCzh0-bvrbHeY85JeBRBSGbYlmoBIEat2xbIELRxMPg",
            "source": "Zacks",
            "post_time_utc": "2023-08-16 11:00:20",
            "stocks_in_news": [
                {
                    "symbol": "MRCY:NASDAQ",
                    "type": "stock",
                    "name": "Mercury Systems Inc",
                    "price": 37.09,
                    "change": 0.92,
                    "change_percent": 2.5436,
                    "previous_close": 36.17,
                    "pre_or_post_market": 37.1,
                    "pre_or_post_market_change": 0.01,
                    "pre_or_post_market_change_percent": 0.027,
                    "last_update_utc": "2023-08-18 00:30:00",
                    "currency": "USD",
                    "exchange": "NASDAQ",
                    "exchange_open": "2023-08-17 09:30:00",
                    "exchange_close": "2023-08-17 16:00:00",
                    "timezone": "America/New_York",
                    "utc_offset_sec": -14400,
                    "country_code": "US",
                    "google_mid": "/m/07zl4cd"
                }
            ]
        },
        {
            "article_title": "Ross Stores, Applied Materials, Moderna: After-hour movers",
            "article_url": "https://finance.yahoo.com/video/ross-stores-applied-materials-moderna-213511907.html",
            "article_photo_url": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTrBuQBSoJ5h1KDBcnikS0qup4YzmDmXN8ahg3vNJST5Q-mlot4T-o23shZSqI",
            "source": "Yahoo Finance",
            "post_time_utc": "2023-08-17 21:35:11",
            "stocks_in_news": [
                {
                    "symbol": "ROST:NASDAQ",
                    "type": "stock",
                    "name": "Ross Stores Inc",
                    "price": 113.06,
                    "change": -2.17,
                    "change_percent": -1.8832,
                    "previous_close": 115.23,
                    "pre_or_post_market": 118.9,
                    "pre_or_post_market_change": 5.84,
                    "pre_or_post_market_change_percent": 5.1654,
                    "last_update_utc": "2023-08-18 00:30:00",
                    "currency": "USD",
                    "exchange": "NASDAQ",
                    "exchange_open": "2023-08-17 09:30:00",
                    "exchange_close": "2023-08-17 16:00:00",
                    "timezone": "America/New_York",
                    "utc_offset_sec": -14400,
                    "country_code": "US",
                    "google_mid": "/m/07zlcth"
                }
            ]
        },
        {
            "article_title": "Tencent Music's quarterly revenue rises but warns of decline ahead",
            "article_url": "https://www.reuters.com/technology/chinas-tencent-music-quarterly-revenue-rises-55-2023-08-15/",
            "article_photo_url": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR2srI8PM7rOzcxj3Nrr23WQ1f5T-sIZRa5EfcDKZq_YEEYZT7Uqs-Z62_G7UM",
            "source": "Reuters",
            "post_time_utc": "2023-08-16 04:47:00",
            "stocks_in_news": [
                {
                    "symbol": "0700:HKG",
                    "type": "stock",
                    "name": "Tencent Holdings Ltd",
                    "price": 328.6,
                    "change": -4.2,
                    "change_percent": -1.262,
                    "previous_close": 332.8,
                    "pre_or_post_market": null,
                    "pre_or_post_market_change": null,
                    "pre_or_post_market_change_percent": null,
                    "last_update_utc": "2023-08-18 04:00:00",
                    "currency": "HKD",
                    "exchange": "HKG",
                    "exchange_open": "2023-08-18 09:30:00",
                    "exchange_close": "2023-08-18 16:00:00",
                    "timezone": "Asia/Hong_Kong",
                    "utc_offset_sec": 28800,
                    "country_code": "HK",
                    "google_mid": "/g/11bc6md9fs"
                }
            ]
        }
    ]
}